# Project information
site_name: Vytamin | Belajar Data Science (WIP)
site_url: https://vytamin.hervyqa.id

# Repository
repo_name: hervyqa/vytamin
repo_url: https://github.com/hervyqa/vytamin

# Copyright
copyright: Copyright &copy; 2023 - Hervy Qurrotul Ainur Rozi

# Configuration
theme:
  name: material
  highlightjs: true
  language: id
  icon:
    edit: material/pencil
    view: material/eye
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
  palette:
    # dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mode terang
    # light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Mode gelap

#Plugins
plugins:
  - tags
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/hervyqa
    - icon: fontawesome/brands/github
      link: https://github.com/hervyqa
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/hervyqa
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.art/@hervyqa
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/hervyqa
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/hervyqa
  consent:
    title: Persetujuan cookie
    actions:
      - accept
      - manage
    description: >-
      Kami juga menggunakan cookie untuk mengenali kunjungan dan preferensi
      Anda yang berulang untuk mengukur efektivitas dokumentasi kami dan
      apakah pengguna menemukan apa yang mereka cari. Dengan persetujuan Anda,
      Anda membantu kami untuk membuat dokumentasi kami lebih baik.

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Page tree
nav:
  - Beranda: index.md
  - Pemrograman:
    - SQL:
      - pemrograman/sql/index.md
      - SQL dasar: pemrograman/sql/sql-dasar/index.md
      - Tipe data: pemrograman/sql/tipe-data/index.md
    - Python:
      - Python dasar: pemrograman/python/index.md
    - R:
      - R dasar: pemrograman/r/index.md
    - Scala:
      - Scala dasar: pemrograman/scala/index.md
    - Julia:
      - Julia dasar: pemrograman/julia/index.md
  - Statistika:
    - Dasar: statistika/dasar/index.md
  - Sample Page: sample.md

