# Project information
site_name: DataSkill | Belajar Data Science (Draft)
site_url: https://dataskill.hervyqa.id

# Repository
repo_name: hervyqa/dataskill
repo_url: https://github.com/hervyqa/dataskill

# Copyright
copyright: Copyright &copy; 2023 - Hervy Qurrotul Ainur Rozi

# Configuration
theme:
  name: material
  highlightjs: true
  language: id
  icon:
    edit: material/pencil
    view: material/eye
  font:
    text: Noto Serif
    code: Hack
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    # dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: dataskill
      toggle:
        icon: material/brightness-4
        name: Mode terang
    # light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dataskill
      toggle:
        icon: material/brightness-7
        name: Mode gelap

extra_css:
  - stylesheets/extra.css

#Plugins
plugins:
  - tags
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/hervyqa
    - icon: fontawesome/brands/github
      link: https://github.com/hervyqa
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/hervyqa
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.art/@hervyqa
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/hervyqa
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/hervyqa
  consent:
    title: Persetujuan cookie
    actions:
      - accept
      - manage
    description: >-
      Kami juga menggunakan cookie untuk mengenali kunjungan dan preferensi
      Anda yang berulang untuk mengukur efektivitas dokumentasi kami dan
      apakah pengguna menemukan apa yang mereka cari. Dengan persetujuan Anda,
      Anda membantu kami untuk membuat dokumentasi kami lebih baik.

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - toc:
      permalink: "#"
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Page tree
nav:
  - Beranda: index.md
  - Python:
    - Pendahuluan:
      - Menyiapkan Pembelajaran: python/menyiapkan-pembelajaran.md
      - Manfaat dan Tujuan Belajar: python/manfaat-dan-tujuan-belajar.md
    - Variabel dan Tipe data:
      - Menulis Variabel: python/menulis-variabel.md
      - Mengenal Jenis Variabel: python/mengenal-jenis-variabel.md
  - R:
    - R dasar: r/index.md
  - Scala:
    - Scala dasar: scala/index.md
  - Julia:
    - Julia dasar: julia/index.md
  - SQL:
    - sql/index.md
    - SQL dasar: sql/sql-dasar.md
    - Tipe data: sql/tipe-data.md
  - PostgreSQL:
    - PostgreSQL dasar: postgresql/index.md
  - MongoDB:
    - MongoDB dasar: mongodb/index.md
  - Statistika:
    - Dasar: statistika/dasar/index.md

